name: Config Suite
type: module
description: Config Suite is a set of improvements to the configuration management sto make it easier to work with.
core: 8.x
core_version_requirement: ^8 || ^9
package: Custom
configure: config_suite.config_suite_form

# Information added by Drupal.org packaging script on 2020-11-13
version: '8.x-1.7'
project: 'config_suite'
datestamp: 1605305415
