quote.settings:
  type: config_object
  label: 'Quote module settings'
  mapping:
    node_types:
      type: sequence
      sequence:
        -type: string
    node_link_display:
      type: boolean
    format:
      type: string
    nest:
      type: integer
