enable: true
description: true
message: true
mailkeys: ''
_core:
  default_config_hash: FWyW0pDoSvPRtqOVlIbk4PxTLiS9S_Ng7zS1JOflWVE
address: jed+wavemetrics@outlier.com
whitelist: 'adam@wavemetrics.com,aclight@gmail.com,aclight+drupal@gmail.com,jim@wavemetrics.com'
